// Costs are explicit modelling assumptions, not broker quotes. All returns are net.
export const HP = [2,3,5,10,20,60,126,252];
export const COSTS = {kr:0.003,us:0.002,jp:0.002};
const countryOf = s => s.endsWith('.kr')?'kr':s.endsWith('.jp')?'jp':'us';
export function sma(c,n){const out=Array(c.length).fill(null);let sum=0;for(let i=0;i<c.length;i++){sum+=c[i];if(i>=n)sum-=c[i-n];if(i>=n-1)out[i]=sum/n;}return out;}
function ema(c,n){let e=c[0];return c.map((v,i)=>e=i?v*2/(n+1)+e*(1-2/(n+1)):v);}
function prior(c,i,n,max=true){let v=max?-Infinity:Infinity;for(let j=Math.max(0,i-n);j<i;j++)v=max?Math.max(v,c[j]):Math.min(v,c[j]);return v;}
function rollingPrior(c,n,max=true){const out=[],q=[];let head=0;for(let i=0;i<c.length;i++){while(head<q.length&&q[head]<i-n)head++;out.push(head<q.length?c[q[head]]:max?-Infinity:Infinity);while(q.length>head&&(max?c[q[q.length-1]]<=c[i]:c[q[q.length-1]]>=c[i]))q.pop();q.push(i);if(head>1024){q.splice(0,head);head=0;}}return out;}
export function normalizeBars(data){if(!Array.isArray(data))return [];const byDate=new Map();for(const b of data){if(!Number.isFinite(b.t)||!Number.isFinite(b.c)||b.c<=0)continue;const t=Math.floor(b.t/86400000)*86400000;byDate.set(t,{...b,t});}return [...byDate.values()].sort((a,b)=>a.t-b.t);}
export function firstEntries(flags){const out=[];for(let i=0;i<flags.length;i++)if(flags[i]&&!flags[i-1])out.push(i);return out;}
export function tradeReturns(events,bars,h,cost,start=0,end=bars.length){const out=[];let lastExit=-1;for(const e of events){const entry=e+1,exit=e+h;if(e<start||entry<=lastExit||exit>=end||exit>=bars.length)continue;const open=bars[entry].o;if(!Number.isFinite(open)||open<=0)continue;out.push({signal:e,entry,exit,ret:bars[exit].c/open-1-cost});lastExit=exit;}return out;}
export function statistics(trades){const r=trades.map(t=>t.ret),n=r.length;const wins=r.filter(v=>v>0),losses=r.filter(v=>v<=0);const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;const avgWin=mean(wins),avgLoss=-mean(losses),ev=mean(r),variance=mean(r.map(v=>(v-ev)**2));return {n,effectiveN:n,winRate:n?wins.length/n:0,avgWin,avgLoss,payoff:avgLoss>0?avgWin/avgLoss:null,ev,netReturn:ev,standardError:n>1?Math.sqrt(variance/(n-1)):null};}
export function evaluate(events,bars,cost){const split=Math.floor(bars.length*0.7),train={},st={};let bh=null;for(const h of HP){train[h]=statistics(tradeReturns(events,bars,h,cost,0,split));if(train[h].n>=20&&(bh===null||train[h].ev>train[bh].ev))bh=h;}if(bh===null)return null;for(const h of HP)st[h]=statistics(tradeReturns(events,bars,h,cost,split,bars.length));const test=st[bh];return {bh,st,train,split,eligible:train[bh].ev>0&&test.n>=10&&test.effectiveN>=8&&test.ev>0,validation:'chronological-holdout',holdoutStart:new Date(bars[split].t).toISOString().slice(0,10)};}
export function signalDefinitions(c){const m200=sma(c,200);const long=c.map((v,i)=>i>=304&&v>m200[i]&&m200[i]>m200[i-105]);const defs=[];const add=(type,badge,label,flags,zones,arr)=>defs.push({type,badge,label,flags,events:firstEntries(flags),zones,arr});
 for(const [typ,fn] of [['SMA',sma],['EMA',ema]])for(const n of [10,20,40,60]){const a=fn(c,n),zones=a.map(v=>v===null?null:[v*.98,v*1.03]);add('ema','이평',`${typ}${n}`,c.map((v,i)=>long[i]&&zones[i]!==null&&v>=zones[i][0]&&v<=zones[i][1]),zones,a);}
 const ath=[];let running=-Infinity;for(const v of c){ath.push(running);running=Math.max(running,v);}
 for(const n of [20,55,252,Infinity]){const hi=n===Infinity?ath:rollingPrior(c,n),zones=c.map((v,i)=>i>=(n===Infinity?20:n)?[hi[i],hi[i]*1.05]:null);add('high','신고가',n===Infinity?'역대최고':`${n}일신고가`,c.map((v,i)=>i>=(n===Infinity?20:n)&&long[i]&&v>=zones[i][0]&&v<=zones[i][1]),zones);}
 const hi=rollingPrior(c,60),lo=rollingPrior(c,60,false),zones=c.map((v,i)=>i>=60?[hi[i],hi[i]*1.05]:null);add('box','박스','60일 박스돌파',c.map((v,i)=>i>=60&&long[i]&&(hi[i]-lo[i])/lo[i]<.2&&v>zones[i][0]&&v<=zones[i][1]),zones);return {defs,long,m200};}
export function analyzeStock(sym,meta,data){const bars=normalizeBars(data);if(bars.length<305)return null;const c=bars.map(b=>b.c),i=c.length-1,price=c[i],country=countryOf(sym),{defs,long,m200}=signalDefinitions(c),m50=sma(c,50);const sigs=[];
 if(long[i])for(const d of defs){const result=evaluate(d.events,bars,COSTS[country]);if(!result?.eligible)continue;const zone=d.zones[i];if(!zone)continue;const entry=d.flags[i]&&!d.flags[i-1];sigs.push({type:d.type,badge:d.badge,desc:`${d.label} · ${result.bh}일 보유`,zoneLo:zone[0],zoneHi:zone[1],status:entry?'in':price<zone[0]?'below':price>zone[1]?'above':'wait',st:result.st,bh:result.bh,train:result.train[result.bh],validation:result.validation,holdoutStart:result.holdoutStart,signalDate:new Date(bars[i].t).toISOString().slice(0,10),execution:'next-session-open',costAssumption:COSTS[country],...(d.arr?{arr:d.arr.slice(-220)}:{})});}
 const rk=n=>i>=n?price/c[i-n]-1:0;return {sym,name:meta[0],sector:meta[1],asset:meta[2]||'stock',country,price,rsRaw:.4*rk(21)+.2*rk(63)+.2*rk(126)+.2*rk(252),rs:50,longOK:long[i],above200:price>m200[i],above50:price>m50[i],newHigh:price>=prior(c,i,252),newLow:price<=prior(c,i,252,false),closes:c.slice(-220),sigs};}
export function regime(data){const b=normalizeBars(data);if(b.length<40)return {ok:false,have:false};const c=b.map(b=>b.c),a=sma(c,10),m=sma(c,20),i=c.length-1;return {ok:a[i]>a[i-3]&&m[i]>m[i-3]&&a[i]>m[i],have:true};}
export function seasonal(sym,meta,data,now=Date.now()){const bars=normalizeBars(data);if(bars.length<2600)return null;const today=new Date(now),year=today.getUTCFullYear(),targets=[];for(let offset=0;offset<=2;offset++){const target=new Date(Date.UTC(year,today.getUTCMonth(),today.getUTCDate()+offset));const rets=[];for(let y=year-1;y>=year-40;y--){const start=Date.UTC(y,target.getUTCMonth(),target.getUTCDate()),e=bars.findIndex(b=>b.t>=start);if(e<0||new Date(bars[e].t).getUTCFullYear()!==y||bars[e].t-start>7*86400000)continue;const exit=e+10;if(exit>=bars.length||new Date(bars[exit].t).getUTCFullYear()>=year)continue;const open=bars[e+1]?.o;if(Number.isFinite(open)&&open>0)rets.push(bars[exit].c/open-1-COSTS[countryOf(sym)]);if(rets.length===10)break;}if(rets.length===10)targets.push({date:target.toISOString().slice(0,10),wr:rets.filter(r=>r>0).length/10,avg:rets.reduce((s,r)=>s+r,0)/10,years:10});}if(!targets.length)return null;const first=targets[0];return {sym,name:meta[0],sector:meta[1],country:countryOf(sym),start:Math.floor((Date.parse(first.date)-Date.UTC(year,0,1))/86400000)+1,nextDate:first.date,hold:10,wr:first.wr,avg:first.avg,years:10,targets,validation:'exploratory-unvalidated',score:first.avg*first.wr};}
